export enum QueryKeys {
  Apis = 'Apis',
  Api = 'Api',
  AgentVersions = 'AgentVersions',
  AgentDefinition = 'AgentDefinition',
  Server = 'Server',
  ApiVersions = 'ApiVersions',
  ApiDefinitions = 'ApiDefinitions',
  ApiDefinition = 'ApiDefinition',
  ApiDeployments = 'ApiDeployments',
  ApiDeploymentEnvironment = 'ApiDeploymentEnvironment',
  ApiSpec = 'ApiSpec',
  ApiSpecUrl = 'ApiSpecUrl',
  ApiAuthScheme = 'ApiAuthScheme',
  ApiAuthSchemeOptions = 'ApiAuthSchemeOptions',
  HttpTestMutation = 'HttpTestMutation',
  MetadataSchemas = 'MetadataSchemas',
  Plugin = 'Plugin',
  LanguageModel = 'LanguageModel',
  SkillEvaluationResult = 'SkillEvaluationResult',
}
